// Demo user data for unauthenticated preview
export const DEMO_CUSTOMER = {
  id: 'demo-customer-1',
  clerkId: 'demo_customer_1',
  email: 'demo@beautybook.com',
  firstName: 'Demo',
  lastName: 'User',
  role: 'CUSTOMER' as const,
  imageUrl: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  customerProfile: {
    id: 'demo-profile-1',
    userId: 'demo-customer-1',
    phone: '+1234567890',
    address: '123 Demo Street',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90001',
    loyaltyPoints: 1250,
    membershipTier: 'SILVER' as const,
    referralCode: 'DEMO2024',
    totalSpent: 450.0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
};

export const DEMO_PROVIDER = {
  id: 'demo-provider-1',
  clerkId: 'demo_provider_1',
  email: 'provider@beautybook.com',
  firstName: 'Sarah',
  lastName: 'Johnson',
  role: 'PROVIDER' as const,
  imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  providerProfile: {
    id: 'demo-provider-profile-1',
    userId: 'demo-provider-1',
    businessName: 'Radiant Beauty Spa',
    title: 'Licensed Esthetician & Spa Owner',
    bio: 'Specialized in facial treatments and skincare with 10+ years of experience.',
    phone: '+1234567890',
    verified: true,
    address: '456 Wellness Ave',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90001',
    experience: 10,
    languages: ['English', 'Spanish'],
    specialties: ['Facial Treatments', 'Skincare', 'Anti-Aging'],
    priceMin: 50,
    priceMax: 300,
    insuranceAccepted: false,
    averageRating: 4.8,
    reviewCount: 127,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
};

export const DEMO_APPOINTMENTS = [
  {
    id: 'demo-apt-1',
    customerId: 'demo-customer-1',
    providerId: 'demo-provider-profile-1',
    serviceId: 'demo-service-1',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    startTime: '10:00',
    endTime: '11:30',
    status: 'CONFIRMED' as const,
    amount: 120.0,
    tipAmount: 0,
    paymentStatus: 'PAID' as const,
    stripeSessionId: null,
    notes: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    service: {
      id: 'demo-service-1',
      name: 'Hydrating Facial',
      description: 'Deep cleansing and moisturizing facial treatment',
      duration: 90,
      price: 120.0,
      category: 'Facial Treatments' as const,
      active: true,
    },
    provider: DEMO_PROVIDER.providerProfile,
  },
  {
    id: 'demo-apt-2',
    customerId: 'demo-customer-1',
    providerId: 'demo-provider-profile-1',
    serviceId: 'demo-service-2',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 14 days ago
    startTime: '14:00',
    endTime: '15:00',
    status: 'COMPLETED' as const,
    amount: 85.0,
    tipAmount: 15.0,
    paymentStatus: 'PAID' as const,
    stripeSessionId: null,
    notes: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    service: {
      id: 'demo-service-2',
      name: 'Express Facial',
      description: 'Quick refreshing facial treatment',
      duration: 60,
      price: 85.0,
      category: 'Facial Treatments' as const,
      active: true,
    },
    provider: DEMO_PROVIDER.providerProfile,
  },
  {
    id: 'demo-apt-3',
    customerId: 'demo-customer-1',
    providerId: 'demo-provider-profile-1',
    serviceId: 'demo-service-3',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    startTime: '15:00',
    endTime: '16:00',
    status: 'SCHEDULED' as const,
    amount: 95.0,
    tipAmount: 0,
    paymentStatus: 'PENDING' as const,
    stripeSessionId: null,
    notes: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    service: {
      id: 'demo-service-3',
      name: 'Microdermabrasion',
      description: 'Exfoliating treatment for smoother skin',
      duration: 60,
      price: 95.0,
      category: 'Facial Treatments' as const,
      active: true,
    },
    provider: DEMO_PROVIDER.providerProfile,
  },
];

export const DEMO_LOYALTY_TRANSACTIONS = [
  {
    id: 'demo-lt-1',
    customerProfileId: 'demo-profile-1',
    type: 'EARNED_BOOKING' as const,
    points: 85,
    description: 'Earned from booking Express Facial',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'demo-lt-2',
    customerProfileId: 'demo-profile-1',
    type: 'EARNED_BOOKING' as const,
    points: 120,
    description: 'Earned from booking Hydrating Facial',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'demo-lt-3',
    customerProfileId: 'demo-profile-1',
    type: 'EARNED_REFERRAL' as const,
    points: 500,
    description: 'Referral bonus',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'demo-lt-4',
    customerProfileId: 'demo-profile-1',
    type: 'REDEEMED' as const,
    points: -200,
    description: 'Redeemed $20 off coupon',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'demo-lt-5',
    customerProfileId: 'demo-profile-1',
    type: 'BONUS' as const,
    points: 100,
    description: 'Welcome bonus',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
];

export const DEMO_ANALYTICS = {
  revenue: {
    total: 8450.0,
    thisMonth: 2340.0,
    lastMonth: 2180.0,
    change: 7.3,
    daily: [
      { date: '2024-01-01', amount: 450, count: 3 },
      { date: '2024-01-02', amount: 680, count: 5 },
      { date: '2024-01-03', amount: 320, count: 2 },
      { date: '2024-01-04', amount: 890, count: 6 },
      { date: '2024-01-05', amount: 550, count: 4 },
      { date: '2024-01-06', amount: 720, count: 5 },
      { date: '2024-01-07', amount: 400, count: 3 },
    ],
  },
  bookings: {
    total: 156,
    thisMonth: 42,
    lastMonth: 38,
    change: 10.5,
  },
  retention: {
    rate: 78.5,
    returningCustomers: 98,
    newCustomers: 27,
  },
  rating: {
    average: 4.8,
    total: 127,
  },
  services: {
    top: [
      { name: 'Hydrating Facial', revenue: 2400, bookings: 20, averageRating: 4.9 },
      { name: 'Deep Tissue Massage', revenue: 2100, bookings: 15, averageRating: 4.8 },
      { name: 'Microdermabrasion', revenue: 1900, bookings: 20, averageRating: 4.7 },
      { name: 'Express Facial', revenue: 1700, bookings: 20, averageRating: 4.6 },
      { name: 'Anti-Aging Treatment', revenue: 1350, bookings: 9, averageRating: 4.9 },
    ],
  },
  staff: [
    { name: 'Sarah Johnson', revenue: 3200, bookings: 28, rating: 4.9 },
    { name: 'Emily Chen', revenue: 2800, bookings: 25, rating: 4.8 },
    { name: 'Maria Garcia', revenue: 2450, bookings: 22, rating: 4.7 },
  ],
  peakHours: [
    { hour: '9:00', bookings: 8 },
    { hour: '10:00', bookings: 15 },
    { hour: '11:00', bookings: 12 },
    { hour: '12:00', bookings: 6 },
    { hour: '13:00', bookings: 7 },
    { hour: '14:00', bookings: 18 },
    { hour: '15:00', bookings: 16 },
    { hour: '16:00', bookings: 14 },
    { hour: '17:00', bookings: 10 },
  ],
  cancellationRate: 12.5,
};

export const isDemoMode = () => {
  if (typeof window === 'undefined') return false;
  return window.location.pathname.startsWith('/demo');
};
