import { Provider, Review, Service } from './types';

// Mock data for development - will be replaced with database queries
export const mockProviders: Provider[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    title: 'Licensed Aesthetician & Dermatologist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    specialty: ['Facial Treatments', 'Skin Care', 'Anti-Aging'],
    rating: 4.9,
    reviewCount: 342,
    experience: 12,
    bio: 'Board-certified dermatologist specializing in medical and cosmetic dermatology with over 12 years of experience. Passionate about helping clients achieve healthy, glowing skin.',
    location: {
      address: '123 Beauty Lane',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
    },
    verified: true,
    insuranceAccepted: ['Aetna', 'Blue Cross', 'Cigna', 'UnitedHealth'],
    languages: ['English', 'Spanish'],
    education: [
      {
        degree: 'Doctor of Medicine (MD)',
        institution: 'UCLA School of Medicine',
        year: 2012,
      },
    ],
    certifications: [
      {
        name: 'Board Certified Dermatologist',
        issuer: 'American Board of Dermatology',
        year: 2015,
      },
    ],
    nextAvailable: new Date(Date.now() + 86400000), // Tomorrow
    priceRange: {
      min: 150,
      max: 500,
    },
  },
  {
    id: '2',
    name: 'Emily Rodriguez',
    title: 'Master Hair Stylist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    specialty: ['Hair Styling', 'Color Specialist', 'Balayage'],
    rating: 4.8,
    reviewCount: 256,
    experience: 8,
    bio: 'Award-winning hair stylist specializing in color transformations and modern cuts. Featured in Vogue and Harper\'s Bazaar.',
    location: {
      address: '456 Style Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
    },
    verified: true,
    insuranceAccepted: [],
    languages: ['English'],
    education: [
      {
        degree: 'Cosmetology License',
        institution: 'Paul Mitchell School',
        year: 2016,
      },
    ],
    certifications: [
      {
        name: 'Certified Balayage Specialist',
        issuer: 'Redken Academy',
        year: 2018,
      },
    ],
    nextAvailable: new Date(Date.now() + 172800000), // 2 days
    priceRange: {
      min: 100,
      max: 350,
    },
  },
  {
    id: '3',
    name: 'Michelle Chen',
    title: 'Licensed Massage Therapist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michelle',
    specialty: ['Deep Tissue Massage', 'Sports Massage', 'Therapeutic Massage'],
    rating: 5.0,
    reviewCount: 189,
    experience: 10,
    bio: 'Certified massage therapist with expertise in sports recovery and chronic pain management. Worked with professional athletes.',
    location: {
      address: '789 Wellness Ave',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
    },
    verified: true,
    insuranceAccepted: ['Aetna', 'Cigna'],
    languages: ['English', 'Mandarin'],
    education: [
      {
        degree: 'Massage Therapy Certification',
        institution: 'National Holistic Institute',
        year: 2014,
      },
    ],
    certifications: [
      {
        name: 'Licensed Massage Therapist',
        issuer: 'California Massage Therapy Council',
        year: 2014,
      },
    ],
    nextAvailable: new Date(Date.now() + 43200000), // 12 hours
    priceRange: {
      min: 80,
      max: 200,
    },
  },
  {
    id: '4',
    name: 'Jessica Williams',
    title: 'Nail Artist & Technician',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    specialty: ['Nail Art', 'Manicure', 'Pedicure'],
    rating: 4.7,
    reviewCount: 412,
    experience: 6,
    bio: 'Creative nail artist specializing in custom designs and long-lasting gel manicures. Instagram @jessicasnails with 50K followers.',
    location: {
      address: '321 Glam Blvd',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
    },
    verified: true,
    insuranceAccepted: [],
    languages: ['English'],
    education: [
      {
        degree: 'Nail Technician License',
        institution: 'Florida Academy of Nail Technology',
        year: 2018,
      },
    ],
    certifications: [
      {
        name: 'Certified Nail Specialist',
        issuer: 'OPI Certified',
        year: 2019,
      },
    ],
    nextAvailable: new Date(Date.now() + 259200000), // 3 days
    priceRange: {
      min: 50,
      max: 150,
    },
  },
  {
    id: '5',
    name: 'David Kim',
    title: 'Makeup Artist & Cosmetologist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    specialty: ['Makeup Artistry', 'Bridal Makeup', 'Special Effects'],
    rating: 4.9,
    reviewCount: 178,
    experience: 9,
    bio: 'Professional makeup artist with experience in fashion, film, and bridal makeup. Featured in multiple fashion weeks.',
    location: {
      address: '555 Glamour Street',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90028',
    },
    verified: true,
    insuranceAccepted: [],
    languages: ['English', 'Korean'],
    education: [
      {
        degree: 'Professional Makeup Artistry',
        institution: 'Make-Up Designory',
        year: 2015,
      },
    ],
    certifications: [
      {
        name: 'Certified Makeup Artist',
        issuer: 'International Makeup Association',
        year: 2016,
      },
    ],
    nextAvailable: new Date(Date.now() + 345600000), // 4 days
    priceRange: {
      min: 120,
      max: 400,
    },
  },
  {
    id: '6',
    name: 'Sophia Martinez',
    title: 'Esthetician & Skincare Specialist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    specialty: ['Facials', 'Chemical Peels', 'Microdermabrasion'],
    rating: 4.8,
    reviewCount: 291,
    experience: 7,
    bio: 'Licensed esthetician specializing in advanced skincare treatments and anti-aging solutions. Certified in multiple laser procedures.',
    location: {
      address: '789 Spa Lane',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
    },
    verified: true,
    insuranceAccepted: ['Blue Cross', 'UnitedHealth'],
    languages: ['English', 'Spanish'],
    education: [
      {
        degree: 'Esthetics License',
        institution: 'Aveda Institute Chicago',
        year: 2017,
      },
    ],
    certifications: [
      {
        name: 'Advanced Esthetics Certification',
        issuer: 'CIDESCO',
        year: 2018,
      },
    ],
    nextAvailable: new Date(Date.now() + 129600000), // 1.5 days
    priceRange: {
      min: 100,
      max: 300,
    },
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    providerId: '1',
    userId: 'u1',
    userName: 'Amanda K.',
    rating: 5,
    comment: 'Dr. Johnson is amazing! She really took the time to understand my skin concerns and created a personalized treatment plan. My skin has never looked better!',
    date: new Date('2024-10-15'),
    verified: true,
    helpful: 24,
  },
  {
    id: '2',
    providerId: '1',
    userId: 'u2',
    userName: 'Robert M.',
    rating: 5,
    comment: 'Professional, knowledgeable, and caring. The office is clean and modern. Highly recommend!',
    date: new Date('2024-10-01'),
    verified: true,
    helpful: 18,
  },
  {
    id: '3',
    providerId: '2',
    userId: 'u3',
    userName: 'Lisa P.',
    rating: 5,
    comment: 'Emily is a color genius! She transformed my hair exactly how I envisioned. The consultation was thorough and she explained every step.',
    date: new Date('2024-10-20'),
    verified: true,
    helpful: 31,
  },
  {
    id: '4',
    providerId: '3',
    userId: 'u4',
    userName: 'Michael B.',
    rating: 5,
    comment: 'Best massage I\'ve ever had! Michelle really knows how to work out those knots. I feel like a new person.',
    date: new Date('2024-10-25'),
    verified: true,
    helpful: 15,
  },
  {
    id: '5',
    providerId: '4',
    userId: 'u5',
    userName: 'Sarah T.',
    rating: 5,
    comment: 'Jessica\'s nail art is incredible! She\'s so creative and the manicure lasted for weeks. Will definitely be back!',
    date: new Date('2024-10-18'),
    verified: true,
    helpful: 22,
  },
  {
    id: '6',
    providerId: '5',
    userId: 'u6',
    userName: 'Jennifer L.',
    rating: 5,
    comment: 'David did my wedding makeup and it was PERFECT! It looked beautiful in person and in photos. Highly recommend!',
    date: new Date('2024-09-30'),
    verified: true,
    helpful: 38,
  },
  {
    id: '7',
    providerId: '6',
    userId: 'u7',
    userName: 'Emily W.',
    rating: 5,
    comment: 'Sophia is a skincare wizard! My skin has improved so much since I started seeing her. She really knows her stuff.',
    date: new Date('2024-10-22'),
    verified: true,
    helpful: 19,
  },
  {
    id: '8',
    providerId: '2',
    userId: 'u8',
    userName: 'Nicole H.',
    rating: 4,
    comment: 'Great stylist! The only reason for 4 stars is the wait time, but the results were worth it.',
    date: new Date('2024-10-12'),
    verified: true,
    helpful: 8,
  },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    name: 'Hydrafacial Treatment',
    description: 'Deep cleansing and hydrating facial treatment',
    duration: 60,
    price: 200,
    category: 'Facial',
  },
  {
    id: 's2',
    name: 'Balayage Hair Color',
    description: 'Natural-looking hair highlights',
    duration: 180,
    price: 250,
    category: 'Hair',
  },
  {
    id: 's3',
    name: 'Deep Tissue Massage',
    description: 'Therapeutic massage for muscle tension',
    duration: 90,
    price: 150,
    category: 'Massage',
  },
  {
    id: 's4',
    name: 'Gel Manicure',
    description: 'Long-lasting gel polish manicure',
    duration: 60,
    price: 65,
    category: 'Nails',
  },
  {
    id: 's5',
    name: 'Bridal Makeup',
    description: 'Full makeup application for your special day',
    duration: 120,
    price: 300,
    category: 'Makeup',
  },
  {
    id: 's6',
    name: 'Chemical Peel',
    description: 'Advanced exfoliating treatment for skin rejuvenation',
    duration: 45,
    price: 180,
    category: 'Facial',
  },
  {
    id: 's7',
    name: 'Swedish Massage',
    description: 'Relaxing full-body massage',
    duration: 60,
    price: 100,
    category: 'Massage',
  },
  {
    id: 's8',
    name: 'Acrylic Full Set',
    description: 'Complete acrylic nail application with design',
    duration: 120,
    price: 85,
    category: 'Nails',
  },
  {
    id: 's9',
    name: 'Haircut & Style',
    description: 'Professional haircut with blow dry and styling',
    duration: 60,
    price: 75,
    category: 'Hair',
  },
  {
    id: 's10',
    name: 'Microneedling',
    description: 'Collagen induction therapy for skin rejuvenation',
    duration: 90,
    price: 350,
    category: 'Facial',
  },
];
